### ISSUE TITLE
Erreur aprés installation (le service ne se lance pas)

### ISSUE THREAD

**Issue by Aeris1One** [YunoHost-Apps/yunomonitor_ynh#3]
Bonjour,
j'ai installé votre script il a quelques minutes mais le service "yunomonitor" apparait "exited", si je tente de le redemarrer j'ai l'erreur suivante : 
```
Jan 08 19:34:48 aeris-one.fr systemd[1]: Starting Run yunomonitor...
Jan 08 19:34:50 aeris-one.fr yunomonitor.py[11682]: INFO:root:CHECKING EACH SERVERS...
Jan 08 19:34:50 aeris-one.fr yunomonitor.py[11682]: INFO:root:[localhost] CONFIGURING...
Jan 08 19:34:50 aeris-one.fr yunomonitor.py[11682]: Exception in thread Thread-1:
Jan 08 19:34:50 aeris-one.fr yunomonitor.py[11682]: Traceback (most recent call last):
Jan 08 19:34:50 aeris-one.fr yunomonitor.py[11682]:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
Jan 08 19:34:50 aeris-one.fr yunomonitor.py[11682]:     self.run()
Jan 08 19:34:50 aeris-one.fr yunomonitor.py[11682]:   File "/opt/yunomonitor/yunomonitor.py", line 448, in run
Jan 08 19:34:50 aeris-one.fr yunomonitor.py[11682]:     self.ynh_maps[self.server] = self._load_monitoring_config()
Jan 08 19:34:50 aeris-one.fr yunomonitor.py[11682]:   File "/opt/yunomonitor/yunomonitor.py", line 488, in _load_monitoring_config
Jan 08 19:34:50 aeris-one.fr yunomonitor.py[11682]:     config = generate_monitoring_config()
Jan 08 19:34:50 aeris-one.fr yunomonitor.py[11682]:   File "/opt/yunomonitor/yunomonitor.py", line 778, in generate_monitoring_config
Jan 08 19:34:50 aeris-one.fr yunomonitor.py[11682]:     "label": app_settings['label'],
Jan 08 19:34:50 aeris-one.fr yunomonitor.py[11682]: KeyError: 'label'
Jan 08 19:34:50 aeris-one.fr yunomonitor.py[11682]: INFO:root:FILTERING...
Jan 08 19:34:50 aeris-one.fr yunomonitor.py[11682]: INFO:root:MAILING...
Jan 08 19:34:50 aeris-one.fr systemd[1]: yunomonitor.service: Succeeded.
Jan 08 19:34:50 aeris-one.fr systemd[1]: Started Run yunomonitor.
```
J'ai utilisé les paramètres par défaut lors de l'installation (avec 2 adresses mails séparées par une virgule et seulement "localhost" en monitored server)

Pouvez-vous m'aider ?

PS: Je n'ai pas trouvé comment configurer Cachet, il n'y a rien dans le Readme de l'upstream :/

**Comment by yalh76** [comment]
should be working with last version
